export enum NotificationTemplateKey {
  RechargeSuccess = 'RechargeSuccess',
  LowBalance = 'LowBalance',
  CriticalBalance = 'CriticalBalance',
  ZeroBalance = 'ZeroBalance',
  OutstandingBalance = 'OutstandingBalance',
  RefundApproved = 'RefundApproved',
  RefundRejected = 'RefundRejected',
  PauseApproved = 'PauseApproved',
  CancellationApproved = 'CancellationApproved',
  BREAKFAST_MENU_REMINDER = 'BREAKFAST_MENU_REMINDER',
  LUNCH_MENU_REMINDER = 'LUNCH_MENU_REMINDER',
  DINNER_MENU_REMINDER = 'DINNER_MENU_REMINDER',
  NEW_MENU_POSTED = 'NEW_MENU_POSTED',
}
