// notification.types.ts

export enum NotificationTemplateKey {
    // Auth
    OTP_SENT = 'OTP_SENT',
    WELCOME = 'WELCOME',

    // Daily Menu
    BREAKFAST_MENU_REMINDER = 'BREAKFAST_MENU_REMINDER',
    LUNCH_MENU_REMINDER = 'LUNCH_MENU_REMINDER',
    DINNER_MENU_REMINDER = 'DINNER_MENU_REMINDER',
    NEW_MENU_POSTED = 'NEW_MENU_POSTED',

    // Payments
    PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
    PAYMENT_PENDING = 'PAYMENT_PENDING',

    // Subscription
    SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
    SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',

    // Meals
    MEAL_DELIVERED = 'MEAL_DELIVERED',
    MEAL_CANCELLED = 'MEAL_CANCELLED',
}